filters:
  - quarto
  - _extensions/person-card/sort-cards.lua

project:
  type: website

website:
  site-url: https://statml.berkeley.edu
  title: "Berkeley StatML"
  sidebar:
    style: docked
    logo: assets/logo/logo.png
    logo-alt: "Logo"
    contents:
      - href: index.qmd
        text: Home
      - href: index.qmd#news
        text: News
      - href: index.qmd#faculty
        text: Faculty
      - href: index.qmd#postdocs
        text: Postdocs
      - href: index.qmd#students
        text: Students
      - href: index.qmd#alumni
        text: Alumni

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: assets/styles.css
    include-after-body: assets/dark-mode-toggle.html
    toc: false # true
